/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AttendanceSchema extends BaseModel {
  static $columns = ['attendanceDate', 'checkInTime', 'checkOutTime', 'createdAt', 'id', 'lateMinutes', 'scanCode', 'status', 'updatedAt', 'userId'] as const
  $columns = AttendanceSchema.$columns
  @column.date()
  declare attendanceDate: DateTime
  @column.dateTime()
  declare checkInTime: DateTime | null
  @column.dateTime()
  declare checkOutTime: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lateMinutes: number
  @column()
  declare scanCode: string | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'message', 'organizationId', 'type'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string
  @column()
  declare organizationId: number
  @column()
  declare type: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'id', 'name', 'phone', 'type', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare type: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'token', 'userId'] as const
  $columns = PasswordResetTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column()
  declare userId: number
}

export class QrSessionSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'expiresAt', 'id', 'isActive', 'organizationId', 'updatedAt'] as const
  $columns = QrSessionSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare organizationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['address', 'authProvider', 'avatarUrl', 'createdAt', 'department', 'email', 'employeeId', 'fullName', 'googleId', 'id', 'organizationId', 'password', 'phone', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare authProvider: any
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare department: string | null
  @column()
  declare email: string
  @column()
  declare employeeId: string | null
  @column()
  declare fullName: string
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare role: any
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
